version: '3.1'
services:
    db:
        image: mysql
        volumes:
            - ./init-sql:/docker-entrypoint-initdb.d
        command: --default-authentication-plugin=mysql_native_password 
        environment:
            MYSQL_ROOT_PASSWORD: it635
    adminer:
        image: adminer
        ports:
            - 8080:8080
    php:
        build: php-apache-mysqli
        ports:
            - 8888:80
        volumes:
            - ./html:/var/www/html/
